### ISSUE TITLE
Coouldn't start after install

### ISSUE THREAD

**Issue by joeitu** [bourgeoa/solid-file-widget#13]
After running
```
npm install
npm start
```
I got the following error:
```
> solid-file-widget@1.0.0 dev
> webpack-dev-server --inline --hot --content-base demo --port 8008

(node:149516) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:8008/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./demo
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (./node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (./node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (./node_modules/webpack/lib/NormalModule.js:471:10)
    at ./node_modules/webpack/lib/NormalModule.js:503:5
    at ./node_modules/webpack/lib/NormalModule.js:358:12
    at ./node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (./node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (./node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (./node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at ./node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at ./node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1

```

**Comment by bourgeoa** [comment]
Thanks for reporting. Do you have the same problem with node < 16

**Comment by joeitu** [comment]
Tried with node @15 and @16. `npm run start` succeed but I get the following error in the console when loading localhost:8008:
![image](https://user-images.githubusercontent.com/60817856/139579017-a3a13dee-bc34-4d0a-b0f6-3276a2459729.png)

**Comment by bourgeoa** [comment]
Sorry I have no time to look at this now.

I just updated the demo link in github to https://bourgeoa.solidcommunity.net/public/solid-file-widget/
It is working with no problem.

Hope this helps.
